parameters:
  env(CONFIRMATION_REGISTRATION): true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    registration:
      confirmation:
        enabled: '%env(CONFIRMATION_REGISTRATION)%'
    from_email:
        address: "%env(MAILER_ADDRESS)%"
        sender_name: "%env(MAILER_NAME)%"