security:
    encoders:
      App\Entity\User: bcrypt

    role_hierarchy:
      ROLE_ADMIN: ROLE_PLAYER

    providers:
      friendsquest_provider:
        entity:
          class: App\Entity\User
          property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
          anonymous: ~
          pattern: ^/login

          json_login:
            check_path: login

          provider: friendsquest_provider

        main:
            pattern: ^/api
            anonymous: ~

            provider: friendsquest_provider

    access_control:
        - { path: ^/api/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
