security:
    encoders:
      App\Entity\User: bcrypt

    role_hierarchy:
      ROLE_ADMIN: ROLE_PLAYER

    providers:
      friendsquest_provider:
        entity:
          class: App\Entity\User
          property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        refresh:
            pattern:  ^/api/token/refresh
            stateless: true
            anonymous: true

        login:
          pattern: ^/login
          stateless: true
          anonymous: true
          json_login:
            check_path: /login
            success_handler: lexik_jwt_authentication.handler.authentication_success
            failure_handler: lexik_jwt_authentication.handler.authentication_failure

          provider: friendsquest_provider

        main:
            pattern: ^/api
            stateless: true
            anonymous: false
            provider: friendsquest_provider
            guard:
              authenticators:
                - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
